deleted list only when clean up is yes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -85,6 +85,7 @@ runs:
         echo "SSH_USER=${{ inputs.ssh_user }}" >> $GITHUB_ENV
         echo "SSH_HOST=${{ inputs.remote_host }}" >> $GITHUB_ENV
         echo "SSH_AUTH=$SSH_AUTH" >> $GITHUB_ENV
+        echo "CLEAN_UP=${{ inputs.cleanup_deleted_files }}" >> $GITHUB_ENV
         echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV
         echo "TAR_FILE=$OUTPUT_DIR/$TAR_NAME" >> $GITHUB_ENV
 
@@ -146,25 +147,27 @@ runs:
         echo "Files to be synchronized:"
         cat "$SYNC_FILES"
         echo "--------End of list--------"
-        
-        touch $DEL_FILE_LIST
-        echo "Preparing a deleted file list..."
-        echo "rsync -av --dry-run --delete --ignore-existing -e 'ssh $SSH_AUTH' $CHECKOUT_DIR/ '$SSH_USER@$SSH_HOST:/$SSH_ROOT_DIR/$DEST_DIR/' | grep '^deleting ' | awk '{print $2}' | grep -v '/$' > $DEL_FILE_LIST"
 
-        rsync -av --dry-run --delete --ignore-existing $EXCLUDE_ARGS \
-          -e "ssh $SSH_AUTH" \
-          $CHECKOUT_DIR/ "$SSH_USER@$SSH_HOST:/$SSH_ROOT_DIR/$DEST_DIR/" \
-          | grep '^deleting ' | awk '{print $2}' | grep -v '/$' > $DEL_FILE_LIST
-        
-        if [[ $? -ne 0 ]]; then
-          echo "Error: Failed to prepare the list of files to delete."
-          exit 1
+        if [ "$CLEAN_UP" = "yes" ]; then
+          touch $DEL_FILE_LIST
+          echo "Preparing a deleted file list..."
+          echo "rsync -av --dry-run --delete --ignore-existing -e 'ssh $SSH_AUTH' $CHECKOUT_DIR/ '$SSH_USER@$SSH_HOST:/$SSH_ROOT_DIR/$DEST_DIR/' | grep '^deleting ' | awk '{print $2}' | grep -v '/$' > $DEL_FILE_LIST"
+  
+          rsync -av --dry-run --delete --ignore-existing $EXCLUDE_ARGS \
+            -e "ssh $SSH_AUTH" \
+            $CHECKOUT_DIR/ "$SSH_USER@$SSH_HOST:/$SSH_ROOT_DIR/$DEST_DIR/" \
+            | grep '^deleting ' | awk '{print $2}' | grep -v '/$' > $DEL_FILE_LIST
+          
+          if [[ $? -ne 0 ]]; then
+            echo "Error: Failed to prepare the list of files to delete."
+            exit 1
+          fi
+          
+          echo $(basename "$DEL_FILE_LIST") >> "$SYNC_FILES"
+          echo "Files to be DELETED:"
+          cat "$DEL_FILE_LIST"
+          echo "--------End of deleted file list--------"
         fi
-
-        echo $(basename "$DEL_FILE_LIST") >> "$SYNC_FILES"
-        echo "Files to be DELETED:"
-        cat "$DEL_FILE_LIST"
-        echo "--------End of deleted file list--------"
 
     - name: Create tar file
       shell: bash
@@ -198,11 +201,10 @@ runs:
       run: |
         echo "Run Server deployer"
         POST_COMMAND=${{inputs.post_deploy_commands}}
-        CLEAN_UP=${{inputs.cleanup_deleted_files}}
         HEALTH_CHECK=${{inputs.enable_health_check}}
         DEPLOYER_SH="/$SSH_ROOT_DIR/deployer.sh"
 
         ssh $SSH_AUTH "$SSH_USER@$SSH_HOST" \ 
-          $DEPLOYER_SH $DEST_DIR $TAR_NAME $CLEAN_UP $HEALTH_CHECK $POST_COMMAND
+          $DEPLOYER_SH $DEST_DIR $TAR_NAME $HEALTH_CHECK $POST_COMMAND
   
         rm -f $TEMP_KEY_FILE
